### ISSUE TITLE
Use proper VMWare hardware profiles to match the base OS.

### ISSUE THREAD

**Issue by techsource12** [covermymeds/mkvm#17]
It appears currently mkvm only uses the "Redhat Enterprise Linux 6 (64-bit)" hardware profile in VMWare regardless of the actual OS version being installed. Can the script be updated to choose the appropriate hardware profile be it "Redhat Enterprise Linux 6 (64-bit)" or "Redhat Enterprise Linux 7 (64-bit)" automatically?

EDIT: This is Chip... logged in as the wrong user.

**Comment by skpy** [comment]
Good catch, @techsource12 .  It looks like the [guestId](http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html) element has supported RHEL7 since API version 5.5.

I have no problem supporting RHEL7 in this way, so long as we clearly identify the vSphere API requirement.
